### ISSUE TITLE
Role Recruitment

### ISSUE THREAD

**Issue by MasSamH** [hackforla/BOP#10]
### Overview
We need to recruit contributors for the BOP project at the outset/or ongoing basis.

### Action Items

- [ ] Keep team Recruiting needs up to date throughout life of project.

### Resources/Instructions
[Project Recruiting Needs](https://docs.google.com/spreadsheets/d/1xnrwTL4kCFhecLQmXwFWVPyWjgc3DC6aQYWq8ZF_QDI/edit#gid=0)

**Comment by ExperimentsInHonesty** [comment]
Recruit for additional product managers

**Comment by Baleja** [comment]
Progress: We started a huge push for product managers so that there are 3 PMs on each project. They will be receiving training in best practices before being put into a project.

**Comment by ExperimentsInHonesty** [comment]
Closing this issue, because HfLA has developed a different system for recuiting, using project boards.  This issue will be replaced by
